print("HI SERVER")
resource.AddSingleFile("sound/avalon.mp3")
resource.AddSingleFile("sound/kars_laugh.mp3")
resource.AddSingleFile("sound/zawarudo.mp3")
resource.AddSingleFile("sound/a10fly.mp3")
resource.AddSingleFile("sound/gau.mp3")
resource.AddSingleFile("sound/whammm.mp3")
resource.AddSingleFile("sound/kars_death.mp3")
resource.AddSingleFile("sound/wings.mp3")
resource.AddSingleFile("sound/wings2.mp3")
resource.AddSingleFile("sound/wings3.mp3")
resource.AddSingleFile("sound/wings4.mp3")
resource.AddSingleFile("sound/low_hp.mp3")
resource.AddSingleFile("sound/powerjump.mp3")
resource.AddSingleFile("sound/tactical.mp3")
resource.AddSingleFile("sound/above.mp3")
resource.AddSingleFile("sound/kingcrimson.mp3")
resource.AddSingleFile("sound/hesitation.mp3")
resource.AddSingleFile("materials/entities/weapon_kars_mask.png")
--lua_run player.GetByID(1):SetHealth(500); lua_run player.GetByID(1):SetArmor(0)